### ISSUE TITLE
Sugestion: replace config.json to config.ini

### ISSUE THREAD

**Issue by gpedro** [Cloakaac/cloak#16]
Users are dumb, if you lose a comma in json, the interpreter can not read.

**Comment by Raggaer** [comment]
True. There are several packages to read INI but I was working on [this](https://github.com/Raggaer/goini)

**Comment by DSpeichert** [comment]
There is already a few well-tested libraries to do that:
* INI: https://github.com/go-gcfg/gcfg/tree/v1.0.0
* JSON, YAML, TOML: http://spf13.com/project/viper
* Powerful, pure TOML: https://github.com/toml-lang/toml

**Comment by Raggaer** [comment]
I think we will go with TOML. what you guys think?

**Comment by DSpeichert** [comment]
TOML seems powerful enough that it supports advanced structures, so I'd risk going with that one.

**Comment by Raggaer** [comment]
Commit f6b9045 enables to use .toml or .json or .yaml using viper there is however one error that I know. on toml

`[[routes]]`

Will work and viper will read it as a 

`[]map[string]interface{}`

But JSON will read it as 

`[]interface{}`

So currently only toml is supported till we figure why or how to prevent this

Also database credentials are now gathered from config.lua file
